systems:
  molecules:
    - - "excited"
      - total_spins: 0
        n_states: 10
        molecules:
          - ["atomic", { charge: 4 }]
  num_walker_per_mol: 400
  init_electron_width: 3.0

vmc:
  spin_penalty:
      enabled: true
      penalty_scale:
        schedule: sigmoid
        init_value: 0.0
        end_value: 0.001
        midpoint_step: 100000
        transition_steps: 10_000
      penalty_type: "snap"
