repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff # Run the linter.
        args: [--fix]
      # Wandb breaks this
      # - id: ruff # Sort improts
      #   name: sort imports with ruff
      #   args: [--select, I, --fix]
      - id: ruff-format # Run the formatter.
