wave_function:
  embedding:
    module: ferminet
    args:
      ferminet:
        activation: tanh
  envelope:
    module: full
  orbitals:
    module: slater
  jastrows:
    - - cusp
      - {}
  meta_network:
    module: null

pretraining:
  epochs: 2000
  basis: ccpvdz
  reparam_loss_scale: 0.0
