#########################################################################################
# Wave function
#########################################################################################
wave_function:
  embedding:
    module: moon # ['moon', 'psiformer', 'ferminet']
    args:
      moon:
        dim: 256
        n_layer: 4
        embedding_dim: 256
        edge_embedding: 32
        edge_hidden_dim: 8
        edge_rbf: 6
        activation: silu
      psiformer:
        dim: 256
        embedding_dim: 256
        n_head: 4
        n_layer: 4
        activation: silu
        attention_implementation: parallel
      ferminet:
        embedding_dim: 256
        hidden_dims:
          - [256, 32]
          - [256, 32]
          - [256, 32]
          - [256, 32]
        activation: silu

  envelope:
    module: efficient # ['efficient', 'full']
    args:
      efficient:
        env_per_nuc: 8
      full: {}

  orbitals:
    module: pfaffian # ['pfaffian', 'slater']
    args:
      pfaffian:
        determinants: 16
        orb_per_charge:
          "1": 2
          "2": 2
          "3": 8
          "4": 8
          "5": 8
          "6": 8
          "7": 8
          "8": 8
          "9": 8
          "10": 8
        hf_match_steps: 50
        hf_match_lr: 1
        hf_match_orbitals: 1
        hf_match_pfaffian: 1.e-3
        hf_match_ema: 0.999
      lowrankpfaffian:
        determinants: 16
        rank: 2
        orb_per_charge:
          "1": 2
          "2": 2
          "3": 8
          "4": 8
          "5": 8
          "6": 8
          "7": 8
          "8": 8
          "9": 8
          "10": 8
        hf_match_steps: 50
        hf_match_lr: 1
        hf_match_orbitals: 1
        hf_match_pfaffian: 1.e-3
        hf_match_ema: 0.999
      slater:
        determinants: 16

  jastrows: # ['mlp', 'cusp']
    - - mlp
      - hidden_dims: [128, 32]
        activation: silu
    - - cusp
      - {}

  meta_network:
    module: meta_gnn # ['meta_gnn', null]
    args:
      meta_gnn:
        message_dim: 32
        embedding_dim: 64
        num_layers: 3
        activation: silu
        n_rbf: 6

#########################################################################################
# VMC
#########################################################################################
vmc:
  epochs: 100_000
  batch_size: 128 # by default full batch

  thermalizing_epochs: 1000

  mcmc:
    steps: 20
    init_width: 0.1
    window_size: 20
    target_pmove: 0.525
    error: 0.025
    blocks: 1
    nonlocal_steps: 0
    nonlocal_step_width: 2.0

  preconditioner:
    module: spring # ['identity', 'cg', 'spring']
    args:
      spring:
        damping: 1.e-3
        decay_factor: 0.99
        dtype: float64
      identity: {}
      cg:
        damping: 1.e-3
        decay_factor: 0.99
        maxiter: 100

  optimizer:
    - transform: scale_by_hyperbolic_schedule
      learning_rate: 0.02
      delay: 10_000
    - transform: clip_by_global_norm
      max_norm: 0.032 # sqrt(1.e-3)

  clipping:
    module: quantile # ['none', 'mean', 'median']
    args:
      none: {}
      mean:
        max_deviation: 5
      median:
        max_deviation: 5
      quantile:
        quantile: 0.95
        max_deviation: 5

#########################################################################################
# Pretraining
#########################################################################################
pretraining:
  epochs: 10000
  batch_size: 128 # by default full batch
  basis: sto-6g

  optimizer:
    - transform: clip_by_global_norm
      max_norm: 1
    - transform: scale_by_adam
    - transform: filter_by_param
      name:
        - kernel
        - pi
        - sigma
      transformations: [scale_by_trust_ratio]
    - transform: filter_by_param
      name: embedding
      transformations: [scale_by_trust_ratio_embeddings]
    - transform: scale_by_hyperbolic_schedule
      learning_rate: 1.e-3
      delay: 10_000

  reparam_loss_scale: 1.e-6
  sample_from: hf

#########################################################################################
# Logging
#########################################################################################
logging:
  wandb: {}
  file:
    directory: null
