systems:
  molecules:
    - ["diatomic", { charge1: 7, charge2: 7, distance: 1.60151 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 1.70828 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 1.81505 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 1.92181 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.02858 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.13535 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.24212 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.34889 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.45565 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.56242 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.66919 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.77595 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.88272 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 2.98949 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.09626 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.20302 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.30979 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.41656 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.52333 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.63009 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.73686 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.84363 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 3.95040 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.05716 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.16393 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.27070 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.37747 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.48423 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.59100 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.69777 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.80454 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 4.91130 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 5.01807 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 5.12484 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 5.23161 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 5.33837 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 5.87221 }]
    - ["diatomic", { charge1: 7, charge2: 7, distance: 6.40605 }]
  num_walker_per_mol: 110
