name: Test

on: [push, pull_request]

jobs:
  # Run CLI test and pytest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5]
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.30"
          enable-cache: true
      - name: Create virtual environment
        run: uv sync
      - name: pytest
        run: uv run pytest --splits 5 --group ${{ matrix.group }}
