name: Test

on: [push, pull_request]

jobs:
  # Run CLI test and pytest
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.30"
          enable-cache: true
      - name: Create virtual environment
        run: uv sync
      - name: pytest
        run: uv run pytest
